export type PoeListIconCategory = "class" | "ascendancy" | "currency";
export type PoeListIconSourceType = "official" | "poe-wiki-original";

export interface PoeListIcon {
  readonly id: string;
  readonly name: string;
  readonly category: PoeListIconCategory;
  readonly path: `/${string}`;
  readonly source: string;
  readonly sourceType: PoeListIconSourceType;
  readonly parentClass?: string;
}

export const poeListIcons = [
  {
    id: "marauder",
    name: "Marauder",
    category: "class",
    path: "/poe/classes/marauder.png",
    source: "https://www.poewiki.net/images/3/30/Marauder_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "duelist",
    name: "Duelist",
    category: "class",
    path: "/poe/classes/duelist.png",
    source: "https://www.poewiki.net/images/e/e0/Duelist_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "ranger",
    name: "Ranger",
    category: "class",
    path: "/poe/classes/ranger.png",
    source: "https://www.poewiki.net/images/4/4b/Ranger_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "shadow",
    name: "Shadow",
    category: "class",
    path: "/poe/classes/shadow.png",
    source: "https://www.poewiki.net/images/7/76/Shadow_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "witch",
    name: "Witch",
    category: "class",
    path: "/poe/classes/witch.png",
    source: "https://www.poewiki.net/images/6/67/Witch_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "templar",
    name: "Templar",
    category: "class",
    path: "/poe/classes/templar.png",
    source: "https://www.poewiki.net/images/b/b3/Templar_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "scion",
    name: "Scion",
    category: "class",
    path: "/poe/classes/scion.png",
    source: "https://www.poewiki.net/images/9/92/Scion_avatar.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "juggernaut",
    name: "Juggernaut",
    category: "ascendancy",
    path: "/poe/ascendancies/juggernaut.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Juggernaut_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Marauder",
  },
  {
    id: "berserker",
    name: "Berserker",
    category: "ascendancy",
    path: "/poe/ascendancies/berserker.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Berserker_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Marauder",
  },
  {
    id: "chieftain",
    name: "Chieftain",
    category: "ascendancy",
    path: "/poe/ascendancies/chieftain.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Chieftain_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Marauder",
  },
  {
    id: "slayer",
    name: "Slayer",
    category: "ascendancy",
    path: "/poe/ascendancies/slayer.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Slayer_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Duelist",
  },
  {
    id: "gladiator",
    name: "Gladiator",
    category: "ascendancy",
    path: "/poe/ascendancies/gladiator.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Gladiator_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Duelist",
  },
  {
    id: "champion",
    name: "Champion",
    category: "ascendancy",
    path: "/poe/ascendancies/champion.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Champion_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Duelist",
  },
  {
    id: "deadeye",
    name: "Deadeye",
    category: "ascendancy",
    path: "/poe/ascendancies/deadeye.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Deadeye_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Ranger",
  },
  {
    id: "pathfinder",
    name: "Pathfinder",
    category: "ascendancy",
    path: "/poe/ascendancies/pathfinder.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Pathfinder_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Ranger",
  },
  {
    id: "warden",
    name: "Warden",
    category: "ascendancy",
    path: "/poe/ascendancies/warden.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Warden_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Ranger",
  },
  {
    id: "assassin",
    name: "Assassin",
    category: "ascendancy",
    path: "/poe/ascendancies/assassin.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Assassin_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Shadow",
  },
  {
    id: "saboteur",
    name: "Saboteur",
    category: "ascendancy",
    path: "/poe/ascendancies/saboteur.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Saboteur_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Shadow",
  },
  {
    id: "trickster",
    name: "Trickster",
    category: "ascendancy",
    path: "/poe/ascendancies/trickster.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Trickster_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Shadow",
  },
  {
    id: "necromancer",
    name: "Necromancer",
    category: "ascendancy",
    path: "/poe/ascendancies/necromancer.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Necromancer_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Witch",
  },
  {
    id: "elementalist",
    name: "Elementalist",
    category: "ascendancy",
    path: "/poe/ascendancies/elementalist.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Elementalist_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Witch",
  },
  {
    id: "occultist",
    name: "Occultist",
    category: "ascendancy",
    path: "/poe/ascendancies/occultist.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Occultist_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Witch",
  },
  {
    id: "inquisitor",
    name: "Inquisitor",
    category: "ascendancy",
    path: "/poe/ascendancies/inquisitor.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Inquisitor_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Templar",
  },
  {
    id: "hierophant",
    name: "Hierophant",
    category: "ascendancy",
    path: "/poe/ascendancies/hierophant.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Hierophant_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Templar",
  },
  {
    id: "guardian",
    name: "Guardian",
    category: "ascendancy",
    path: "/poe/ascendancies/guardian.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Guardian_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Templar",
  },
  {
    id: "ascendant",
    name: "Ascendant",
    category: "ascendancy",
    path: "/poe/ascendancies/ascendant.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Ascendant_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Scion",
  },
  {
    id: "reliquarian",
    name: "Reliquarian",
    category: "ascendancy",
    path: "/poe/ascendancies/reliquarian.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Reliquarian_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Scion",
  },
  {
    id: "luminary",
    name: "Luminary",
    category: "ascendancy",
    path: "/poe/ascendancies/luminary.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Luminary_avatar.png",
    sourceType: "poe-wiki-original",
    parentClass: "Scion",
  },
  {
    id: "mirror-of-kalandra",
    name: "Mirror of Kalandra",
    category: "currency",
    path: "/poe/currency/mirror-of-kalandra.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Mirror%20of%20Kalandra%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "divine-orb",
    name: "Divine Orb",
    category: "currency",
    path: "/poe/currency/divine-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Divine%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "exalted-orb",
    name: "Exalted Orb",
    category: "currency",
    path: "/poe/currency/exalted-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Exalted%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "chaos-orb",
    name: "Chaos Orb",
    category: "currency",
    path: "/poe/currency/chaos-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Chaos%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-annulment",
    name: "Orb of Annulment",
    category: "currency",
    path: "/poe/currency/orb-of-annulment.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Annulment%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-alchemy",
    name: "Orb of Alchemy",
    category: "currency",
    path: "/poe/currency/orb-of-alchemy.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Alchemy%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-fusing",
    name: "Orb of Fusing",
    category: "currency",
    path: "/poe/currency/orb-of-fusing.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Fusing%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-regret",
    name: "Orb of Regret",
    category: "currency",
    path: "/poe/currency/orb-of-regret.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Regret%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-scouring",
    name: "Orb of Scouring",
    category: "currency",
    path: "/poe/currency/orb-of-scouring.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Scouring%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-alteration",
    name: "Orb of Alteration",
    category: "currency",
    path: "/poe/currency/orb-of-alteration.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Alteration%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-chance",
    name: "Orb of Chance",
    category: "currency",
    path: "/poe/currency/orb-of-chance.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Chance%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "chromatic-orb",
    name: "Chromatic Orb",
    category: "currency",
    path: "/poe/currency/chromatic-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Chromatic%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "jewellers-orb",
    name: "Jeweller's Orb",
    category: "currency",
    path: "/poe/currency/jewellers-orb.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Jeweller%27s%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "vaal-orb",
    name: "Vaal Orb",
    category: "currency",
    path: "/poe/currency/vaal-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Vaal%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "blessed-orb",
    name: "Blessed Orb",
    category: "currency",
    path: "/poe/currency/blessed-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Blessed%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "regal-orb",
    name: "Regal Orb",
    category: "currency",
    path: "/poe/currency/regal-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Regal%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "gemcutters-prism",
    name: "Gemcutter's Prism",
    category: "currency",
    path: "/poe/currency/gemcutters-prism.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Gemcutter%27s%20Prism%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "glassblowers-bauble",
    name: "Glassblower's Bauble",
    category: "currency",
    path: "/poe/currency/glassblowers-bauble.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Glassblower%27s%20Bauble%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "cartographers-chisel",
    name: "Cartographer's Chisel",
    category: "currency",
    path: "/poe/currency/cartographers-chisel.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Cartographer%27s%20Chisel%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "ancient-orb",
    name: "Ancient Orb",
    category: "currency",
    path: "/poe/currency/ancient-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Ancient%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "harbingers-orb",
    name: "Harbinger's Orb",
    category: "currency",
    path: "/poe/currency/harbingers-orb.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Harbinger%27s%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-horizons",
    name: "Orb of Horizons",
    category: "currency",
    path: "/poe/currency/orb-of-horizons.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Horizons%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "fracturing-orb",
    name: "Fracturing Orb",
    category: "currency",
    path: "/poe/currency/fracturing-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Fracturing%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "sacred-orb",
    name: "Sacred Orb",
    category: "currency",
    path: "/poe/currency/sacred-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Sacred%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "awakeners-orb",
    name: "Awakener's Orb",
    category: "currency",
    path: "/poe/currency/awakeners-orb.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Awakener%27s%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-dominance",
    name: "Orb of Dominance",
    category: "currency",
    path: "/poe/currency/orb-of-dominance.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Dominance%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "eldritch-exalted-orb",
    name: "Eldritch Exalted Orb",
    category: "currency",
    path: "/poe/currency/eldritch-exalted-orb.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Eldritch%20Exalted%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "eldritch-chaos-orb",
    name: "Eldritch Chaos Orb",
    category: "currency",
    path: "/poe/currency/eldritch-chaos-orb.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Eldritch%20Chaos%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "eldritch-orb-of-annulment",
    name: "Eldritch Orb of Annulment",
    category: "currency",
    path: "/poe/currency/eldritch-orb-of-annulment.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Eldritch%20Orb%20of%20Annulment%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "scroll-of-wisdom",
    name: "Scroll of Wisdom",
    category: "currency",
    path: "/poe/currency/scroll-of-wisdom.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Scroll%20of%20Wisdom%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "portal-scroll",
    name: "Portal Scroll",
    category: "currency",
    path: "/poe/currency/portal-scroll.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Portal%20Scroll%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-transmutation",
    name: "Orb of Transmutation",
    category: "currency",
    path: "/poe/currency/orb-of-transmutation.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Transmutation%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-augmentation",
    name: "Orb of Augmentation",
    category: "currency",
    path: "/poe/currency/orb-of-augmentation.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Augmentation%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-binding",
    name: "Orb of Binding",
    category: "currency",
    path: "/poe/currency/orb-of-binding.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Binding%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "blacksmiths-whetstone",
    name: "Blacksmith's Whetstone",
    category: "currency",
    path: "/poe/currency/blacksmiths-whetstone.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Blacksmith%27s%20Whetstone%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "veiled-orb",
    name: "Veiled Orb",
    category: "currency",
    path: "/poe/currency/veiled-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Veiled%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "tailors-orb",
    name: "Tailoring Orb",
    category: "currency",
    path: "/poe/currency/tailors-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Tailoring%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "tempering-orb",
    name: "Tempering Orb",
    category: "currency",
    path: "/poe/currency/tempering-orb.png",
    source: "https://www.poewiki.net/wiki/Special:FilePath/Tempering%20Orb%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-conflict",
    name: "Orb of Conflict",
    category: "currency",
    path: "/poe/currency/orb-of-conflict.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Conflict%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "orb-of-unmaking",
    name: "Orb of Unmaking",
    category: "currency",
    path: "/poe/currency/orb-of-unmaking.png",
    source:
      "https://www.poewiki.net/wiki/Special:FilePath/Orb%20of%20Unmaking%20inventory%20icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "armourers-scrap",
    name: "Armourer's Scrap",
    category: "currency",
    path: "/poe/currency/armourers-scrap.png",
    source: "https://www.poewiki.net/images/8/88/Armourer%27s_Scrap_inventory_icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "instilling-orb",
    name: "Instilling Orb",
    category: "currency",
    path: "/poe/currency/instilling-orb.png",
    source: "https://www.poewiki.net/images/7/7f/Instilling_Orb_inventory_icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "enkindling-orb",
    name: "Enkindling Orb",
    category: "currency",
    path: "/poe/currency/enkindling-orb.png",
    source: "https://www.poewiki.net/images/b/b3/Enkindling_Orb_inventory_icon.png",
    sourceType: "poe-wiki-original",
  },
  {
    id: "stacked-deck",
    name: "Stacked Deck",
    category: "currency",
    path: "/poe/currency/stacked-deck.png",
    source: "https://www.poewiki.net/images/6/60/Stacked_Deck_inventory_icon.png",
    sourceType: "poe-wiki-original",
  },
] as const satisfies readonly PoeListIcon[];

export type PoeListIconOption = {
  readonly id: string;
  readonly label: string;
  readonly src: `/${string}`;
  readonly category: PoeListIconCategory;
};

export const poeListIconOptions: PoeListIconOption[] = poeListIcons.map((icon) => ({
  id: icon.id,
  label: icon.name,
  src: icon.path,
  category: icon.category,
}));
