/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    CaptureUnavailableBanner: typeof import('./src/components/shared/CaptureUnavailableBanner.vue')['default']
    ExportSheet: typeof import('./src/components/mine/ExportSheet.vue')['default']
    ImportSheet: typeof import('./src/components/mine/ImportSheet.vue')['default']
    ItemRow: typeof import('./src/components/mine/ItemRow.vue')['default']
    MineTab: typeof import('./src/components/mine/MineTab.vue')['default']
    OverviewMarkdown: typeof import('./src/components/mine/OverviewMarkdown.vue')['default']
    Pill: typeof import('./src/components/shared/Pill.vue')['default']
    SaveModal: typeof import('./src/components/mine/SaveModal.vue')['default']
    SettingsPopover: typeof import('./src/components/settings/SettingsPopover.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCollapsible: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.0_c9738d24f09c8eeb4e61f33364be055b/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
